const LANGUAGE_KEY = "hof_language";

const TEXT = {
  en: {
    home: "Home",
    projects: "Projects",
    myProjects: "My Projects",
    upload: "Upload",
    monitor: "Monitor",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    language: "Language",
    english: "English",
    german: "German",
    allDepartments: "All Departments",
    allTags: "All Tags",
    searchProjects: "Search projects, students, or topics",
    projectsHeading: "Explore Projects",
    myProjectsHeading: "My Projects",
    myProjectsSubheading: "Only your uploaded projects are shown here.",
    noProjects: "No projects found.",
    page: "Page",
    of: "of",
    prev: "Prev",
    next: "Next",
    profileTitle: "User Profile",
    profileSubtitle: "Read-only profile details sourced from your active session.",
    userDetails: "User Details",
    academicDetails: "Academic Details",
    fullName: "Full Name",
    email: "Email",
    role: "Role",
    dob: "Date of Birth",
    regNumber: "Registration Number",
    batch: "Batch",
    course: "Course",
    timezone: "Timezone",
    notAvailable: "Not available",
    student: "Student",
    faculty: "Faculty",
    admin: "Admin",
    viewer: "Viewer",
    back: "Back",
    description: "Description",
    team: "Team",
    documentation: "Documentation",
    resources: "Resources",
    comments: "Comments",
    buildLogs: "Build Logs",
    solo: "Solo",
    projectOverview: "Project Overview",
    noDescription: "No description provided.",
    demoVideo: "Demo Video",
    techStack: "Tech Stack",
    teamMembers: "Team Members",
    noTeammates: "No teammates listed.",
    referenceLinks: "Reference Links",
    noResourceLinks: "No resource links added.",
    resourceFiles: "Resource Files",
    noFilesAdded: "No files added.",
    openResourceFile: "Open resource file",
    projectComments: "Project Comments",
    noComments: "No comments yet.",
    addComment: "Add your comment...",
    posting: "Posting...",
    postComment: "Post Comment",
    loginToComment: "Login to add a comment.",
    runControls: "Run Controls",
    stopping: "Stopping...",
    starting: "Starting...",
    stopProject: "Stop Project",
    startProject: "Start Project",
    running: "Running",
    notRunning: "Not running",
    openLiveUrl: "Open Live URL",
    shareProject: "Share Project",
    evaluationPanel: "Evaluation Panel",
    addTeacherRemark: "Add teacher remark...",
    publishToStudent: "Publish to student now",
    saving: "Saving...",
    saveRemark: "Save Remark",
    noRemarks: "No remarks yet.",
    published: "Published",
    draft: "Draft",
    unpublish: "Unpublish",
    publish: "Publish",
    buildLog: "Build Log",
    deployLog: "Deploy Log",
    noBuildLogs: "No build logs available.",
    noDeployLogs: "No deploy logs available.",
    noImages: "No project images uploaded",
    browserNoVideo: "Your browser does not support embedded video playback.",
    unknown: "Unknown",
    general: "General",
    landingHeadlineTop: "Showcase Your Innovation.",
    landingHeadlineBottom: "Shape Your Future.",
    landingSubtitle:
      "A collaborative platform for SRH ACS and ADS students to upload, deploy, review, and present impactful academic projects.",
    landingSearchPlaceholder: "Search by project name, tech, or topic...",
    explore: "Explore",
    forStudents: "For Students",
    forStudentsText: "Upload your capstone work with GitHub or ZIP and run it live.",
    forFaculty: "For Faculty",
    forFacultyText: "Review submissions, monitor deployment health, and guide teams.",
    forCommunity: "For Community",
    forCommunityText: "Discover cross-discipline projects from ACS and ADS cohorts.",
    latestProjects: "Latest Projects",
    viewAllProjects: "View All Projects",
    noImage: "No Image",
    unknownStudent: "Unknown Student",
    all: "All",
    teamLabel: "Team",
    loginHeroTitleTop: "Elevate Your",
    loginHeroTitleBottom: "Academic Journey.",
    loginHeroText:
      "Collaborate, review, and innovate with your peers and professors on the SRH Applied Sciences platform.",
    welcomeBack: "Welcome Back",
    signInContinue: "Sign in to continue to SRH Project Hub.",
    srhEmail: "SRH Email",
    emailPlaceholder: "e.g. student@stud.hochschule-heidelberg.de",
    password: "Password",
    passwordPlaceholder: "Enter password",
    signingIn: "Signing in...",
    signIn: "Sign In",
    orSignInWith: "or sign in with",
    newHere: "New here?",
    createViewerAccount: "Create a viewer account",
    loginFailed: "Login failed",
    registerHeroTitleTop: "Join the",
    registerHeroTitleBottom: "Project Community.",
    registerHeroText:
      "Create an account to explore projects and comment on submissions. Domain-based roles are assigned automatically.",
    createAccount: "Create Account",
    signUpHint: "Sign up to view and discuss projects.",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "Your name",
    dateOfBirth: "Date of Birth",
    minPasswordPlaceholder: "Minimum 6 characters",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Re-enter password",
    creating: "Creating...",
    alreadyHaveAccount: "Already have an account?",
    nameRequired: "Name is required.",
    emailRequired: "Email is required.",
    dobRequired: "Date of birth is required.",
    passwordMin: "Password must be at least 6 characters.",
    passwordsNoMatch: "Passwords do not match.",
    registrationFailed: "Registration failed",
    accountCreated: "Account created",
    pleaseSignIn: "Please sign in.",
    uploadTitle: "Write Project Documentation",
    stepOf: "Step",
    stepDivider: "of",
    submittingProject: "Submitting project...",
    submittingProjectText: "Please wait while we upload files and queue your build.",
    submissionProgress: "Submission Progress",
    generalInfo: "General Info",
    assetsMedia: "Assets & Media",
    reviewSubmit: "Review & Submit",
    clearDraft: "Clear Draft",
    draftCleared: "Draft cleared.",
    previousBuildFailed: "Previous build failed",
    fixIssueUploadAgain: "Fix the issue and upload again.",
    studentName: "Student Name",
    registrationNumber: "Registration Number",
    projectTitle: "Project Title",
    projectDescription: "Project Description",
    githubUrlOptional: "GitHub URL (optional if ZIP used)",
    selectedZip: "Selected ZIP",
    selectTeamMates: "Select Team Mates",
    selectTeammate: "Select teammate",
    addTeammate: "Add Teammate",
    onlyStudentsListed: "Only students from your course and batch are listed.",
    noTeammatesSolo: "No teammates added (solo by default).",
    remove: "Remove",
    imageGallery: "Image Gallery",
    projectDemoVideoOptional: "Project Demo Video (optional)",
    documentationPlaceholder: "Write project documentation, architecture notes, setup steps...",
    resourcesTitle: "Resources",
    resourceLinksPlaceholder: "Paste reference links, one per line",
    referencePdfsNotes: "Reference PDFs / Notes (optional)",
    editGeneralInfo: "Edit General Info",
    editAssetsMedia: "Edit Assets & Media",
    finalReview: "Final Review",
    title: "Title",
    tag: "Tag",
    source: "Source",
    soloProject: "Solo project",
    images: "Images",
    video: "Video",
    notAdded: "Not added",
    links: "Links",
    files: "Files",
    backBtn: "Back",
    nextBtn: "Next",
    submitProject: "Submit Project",
    provideGithubOrZip: "Provide GitHub URL or ZIP file.",
    onlyOneSource: "Use only one source: GitHub URL or ZIP.",
    validGithubUrl: "Enter a valid GitHub repo URL (example: https://github.com/owner/repo).",
    selectTechnology: "Select at least one technology.",
    fixValidationErrors: "Fix file validation errors before continuing.",
    pleaseLoginFirst: "Please login first.",
    uploadFailed: "Upload failed",
    selectedTeammateNotFound: "Selected teammate not found.",
    teammateAlreadyAdded: "Teammate already added.",
    ownerAlreadyIncluded: "You are already included as project owner.",
    teammateMustMatchCourse: "Teammate must be from your course.",
    teammateMustMatchBatch: "Teammate must be from your batch.",
    buildLogsPage: "Build Logs",
    loadingBuildStatus: "Loading build status...",
    buildQueued: "Build is queued...",
    buildInProgress: "Build in progress...",
    buildCompletedReady: "Build completed. Project is ready to start.",
    currentStatus: "Current status",
    liveStream: "Live stream",
    buildFailedReview: "Build failed. Review logs and update your upload.",
    backToUpload: "Back To Upload",
    buildCompletedSuccess: "Build completed successfully.",
    openProject: "Open Project",
    noLogsYet: "No logs yet...",
    noDeployLogsYet: "No deploy logs yet...",
    couldNotFetchBuildStatus: "Unable to fetch build status. Please retry.",
    opsMonitor: "Ops Monitor",
    appliedSciences: "Applied Sciences",
    useAdminToken: "Use an admin token to load live quota metrics.",
    pasteAdminJwt: "Paste admin JWT token",
    loading: "Loading...",
    loadMonitor: "Load Monitor",
    trackedUsers: "Tracked Users",
    queuedBuilding: "Queued/Building",
    runningProjects: "Running Projects",
    courseQuotaHealth: "Course Quota Health (ACS / ADS)",
    runningSuffix: "running",
    userQuotaRiskTable: "User Quota Risk Table",
    user: "User",
    uploads24h: "Uploads 24h",
    queueLoad: "Queue Load",
    risk: "Risk",
    enterAdminToken: "Enter admin JWT token.",
    failedMonitoringData: "Failed to load monitoring data.",
    ssoPlaceholder: "SSO will be wired once credentials are provided.",
  },
  de: {
    home: "Startseite",
    projects: "Projekte",
    myProjects: "Meine Projekte",
    upload: "Hochladen",
    monitor: "Monitor",
    login: "Anmelden",
    logout: "Abmelden",
    profile: "Profil",
    language: "Sprache",
    english: "Englisch",
    german: "Deutsch",
    allDepartments: "Alle Bereiche",
    allTags: "Alle Tags",
    searchProjects: "Projekte, Studierende oder Themen suchen",
    projectsHeading: "Projekte entdecken",
    myProjectsHeading: "Meine Projekte",
    myProjectsSubheading: "Hier werden nur deine hochgeladenen Projekte angezeigt.",
    noProjects: "Keine Projekte gefunden.",
    page: "Seite",
    of: "von",
    prev: "Zurück",
    next: "Weiter",
    profileTitle: "Benutzerprofil",
    profileSubtitle: "Schreibgeschützte Profildaten aus deiner aktuellen Sitzung.",
    userDetails: "Benutzerdetails",
    academicDetails: "Studiendetails",
    fullName: "Vollständiger Name",
    email: "E-Mail",
    role: "Rolle",
    dob: "Geburtsdatum",
    regNumber: "Matrikelnummer",
    batch: "Jahrgang",
    course: "Studiengang",
    timezone: "Zeitzone",
    notAvailable: "Nicht verfügbar",
    student: "Student",
    faculty: "Dozent",
    admin: "Admin",
    viewer: "Besucher",
    back: "Zurück",
    description: "Beschreibung",
    team: "Team",
    documentation: "Dokumentation",
    resources: "Ressourcen",
    comments: "Kommentare",
    buildLogs: "Build-Protokolle",
    solo: "Einzeln",
    projectOverview: "Projektübersicht",
    noDescription: "Keine Beschreibung vorhanden.",
    demoVideo: "Demo-Video",
    techStack: "Technologie-Stack",
    teamMembers: "Teammitglieder",
    noTeammates: "Keine Teammitglieder eingetragen.",
    referenceLinks: "Referenzlinks",
    noResourceLinks: "Keine Referenzlinks hinzugefügt.",
    resourceFiles: "Ressourcendateien",
    noFilesAdded: "Keine Dateien hinzugefügt.",
    openResourceFile: "Ressourcendatei öffnen",
    projectComments: "Projektkommentare",
    noComments: "Noch keine Kommentare vorhanden.",
    addComment: "Deinen Kommentar hinzufügen...",
    posting: "Wird gesendet...",
    postComment: "Kommentar senden",
    loginToComment: "Bitte anmelden, um einen Kommentar zu schreiben.",
    runControls: "Projektsteuerung",
    stopping: "Wird gestoppt...",
    starting: "Wird gestartet...",
    stopProject: "Projekt stoppen",
    startProject: "Projekt starten",
    running: "Läuft",
    notRunning: "Nicht aktiv",
    openLiveUrl: "Live-URL öffnen",
    shareProject: "Projekt teilen",
    evaluationPanel: "Bewertungsbereich",
    addTeacherRemark: "Lehrenden-Kommentar hinzufügen...",
    publishToStudent: "Sofort für Studierende freigeben",
    saving: "Wird gespeichert...",
    saveRemark: "Kommentar speichern",
    noRemarks: "Noch keine Bemerkungen vorhanden.",
    published: "Veröffentlicht",
    draft: "Entwurf",
    unpublish: "Verbergen",
    publish: "Veröffentlichen",
    buildLog: "Build-Protokoll",
    deployLog: "Deploy-Protokoll",
    noBuildLogs: "Keine Build-Protokolle verfügbar.",
    noDeployLogs: "Keine Deploy-Protokolle verfügbar.",
    noImages: "Keine Projektbilder hochgeladen",
    browserNoVideo: "Dein Browser unterstützt keine eingebettete Videowiedergabe.",
    unknown: "Unbekannt",
    general: "Allgemein",
    landingHeadlineTop: "Zeige deine Innovation.",
    landingHeadlineBottom: "Gestalte deine Zukunft.",
    landingSubtitle:
      "Eine kollaborative Plattform für SRH-Studierende aus ACS und ADS, um akademische Projekte hochzuladen, bereitzustellen, zu bewerten und zu präsentieren.",
    landingSearchPlaceholder: "Nach Projektname, Technologie oder Thema suchen...",
    explore: "Entdecken",
    forStudents: "Für Studierende",
    forStudentsText: "Lade deine Abschlussarbeit per GitHub oder ZIP hoch und starte sie live.",
    forFaculty: "Für Lehrende",
    forFacultyText: "Prüfe Einreichungen, überwache den Deploy-Status und begleite Teams.",
    forCommunity: "Für die Community",
    forCommunityText: "Entdecke interdisziplinäre Projekte aus den ACS- und ADS-Jahrgängen.",
    latestProjects: "Neueste Projekte",
    viewAllProjects: "Alle Projekte anzeigen",
    noImage: "Kein Bild",
    unknownStudent: "Unbekannter Studierender",
    all: "Alle",
    teamLabel: "Team",
    loginHeroTitleTop: "Stärke deine",
    loginHeroTitleBottom: "akademische Reise.",
    loginHeroText:
      "Arbeite mit deinen Kommilitoninnen, Kommilitonen und Lehrenden auf der SRH Applied Sciences Plattform zusammen, prüfe Projekte und entwickle neue Ideen.",
    welcomeBack: "Willkommen zurück",
    signInContinue: "Melde dich an, um mit dem SRH Project Hub fortzufahren.",
    srhEmail: "SRH-E-Mail",
    emailPlaceholder: "z. B. student@stud.hochschule-heidelberg.de",
    password: "Passwort",
    passwordPlaceholder: "Passwort eingeben",
    signingIn: "Anmeldung läuft...",
    signIn: "Anmelden",
    orSignInWith: "oder anmelden mit",
    newHere: "Neu hier?",
    createViewerAccount: "Besucher-Konto erstellen",
    loginFailed: "Anmeldung fehlgeschlagen",
    registerHeroTitleTop: "Werde Teil der",
    registerHeroTitleBottom: "Projekt-Community.",
    registerHeroText:
      "Erstelle ein Konto, um Projekte zu entdecken und Kommentare zu Einreichungen zu schreiben. Rollen werden anhand der Domain automatisch zugewiesen.",
    createAccount: "Konto erstellen",
    signUpHint: "Registriere dich, um Projekte anzusehen und zu diskutieren.",
    fullNameLabel: "Vollständiger Name",
    fullNamePlaceholder: "Dein Name",
    dateOfBirth: "Geburtsdatum",
    minPasswordPlaceholder: "Mindestens 6 Zeichen",
    confirmPassword: "Passwort bestätigen",
    confirmPasswordPlaceholder: "Passwort erneut eingeben",
    creating: "Wird erstellt...",
    alreadyHaveAccount: "Du hast bereits ein Konto?",
    nameRequired: "Name ist erforderlich.",
    emailRequired: "E-Mail ist erforderlich.",
    dobRequired: "Geburtsdatum ist erforderlich.",
    passwordMin: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    passwordsNoMatch: "Die Passwörter stimmen nicht überein.",
    registrationFailed: "Registrierung fehlgeschlagen",
    accountCreated: "Konto erstellt",
    pleaseSignIn: "Bitte melde dich an.",
    uploadTitle: "Projektdokumentation erstellen",
    stepOf: "Schritt",
    stepDivider: "von",
    submittingProject: "Projekt wird übermittelt...",
    submittingProjectText: "Bitte warte, während wir Dateien hochladen und den Build einreihen.",
    submissionProgress: "Einreichungsfortschritt",
    generalInfo: "Allgemeine Angaben",
    assetsMedia: "Medien & Dateien",
    reviewSubmit: "Prüfen & Absenden",
    clearDraft: "Entwurf löschen",
    draftCleared: "Entwurf gelöscht.",
    previousBuildFailed: "Vorheriger Build fehlgeschlagen",
    fixIssueUploadAgain: "Behebe das Problem und lade das Projekt erneut hoch.",
    studentName: "Name des Studierenden",
    registrationNumber: "Matrikelnummer",
    projectTitle: "Projekttitel",
    projectDescription: "Projektbeschreibung",
    githubUrlOptional: "GitHub-URL (optional bei ZIP-Nutzung)",
    selectedZip: "Ausgewählte ZIP",
    selectTeamMates: "Teammitglieder auswählen",
    selectTeammate: "Teammitglied auswählen",
    addTeammate: "Teammitglied hinzufügen",
    onlyStudentsListed: "Es werden nur Studierende aus deinem Studiengang und Jahrgang angezeigt.",
    noTeammatesSolo: "Keine Teammitglieder hinzugefügt (standardmäßig Einzelprojekt).",
    remove: "Entfernen",
    imageGallery: "Bildergalerie",
    projectDemoVideoOptional: "Projekt-Demo-Video (optional)",
    documentationPlaceholder: "Projekt-Dokumentation, Architekturhinweise und Setup-Schritte eingeben...",
    resourcesTitle: "Ressourcen",
    resourceLinksPlaceholder: "Referenzlinks einfügen, einer pro Zeile",
    referencePdfsNotes: "Referenz-PDFs / Notizen (optional)",
    editGeneralInfo: "Allgemeine Angaben bearbeiten",
    editAssetsMedia: "Medien & Dateien bearbeiten",
    finalReview: "Abschlussprüfung",
    title: "Titel",
    tag: "Tag",
    source: "Quelle",
    soloProject: "Einzelprojekt",
    images: "Bilder",
    video: "Video",
    notAdded: "Nicht hinzugefügt",
    links: "Links",
    files: "Dateien",
    backBtn: "Zurück",
    nextBtn: "Weiter",
    submitProject: "Projekt absenden",
    provideGithubOrZip: "Bitte GitHub-URL oder ZIP-Datei angeben.",
    onlyOneSource: "Bitte nur eine Quelle verwenden: GitHub-URL oder ZIP.",
    validGithubUrl: "Bitte eine gültige GitHub-Repository-URL eingeben (Beispiel: https://github.com/owner/repo).",
    selectTechnology: "Bitte mindestens eine Technologie auswählen.",
    fixValidationErrors: "Bitte zuerst die Datei-Validierungsfehler beheben.",
    pleaseLoginFirst: "Bitte zuerst anmelden.",
    uploadFailed: "Upload fehlgeschlagen",
    selectedTeammateNotFound: "Ausgewähltes Teammitglied wurde nicht gefunden.",
    teammateAlreadyAdded: "Teammitglied wurde bereits hinzugefügt.",
    ownerAlreadyIncluded: "Du bist bereits als Projektinhaber enthalten.",
    teammateMustMatchCourse: "Das Teammitglied muss aus deinem Studiengang sein.",
    teammateMustMatchBatch: "Das Teammitglied muss aus deinem Jahrgang sein.",
    buildLogsPage: "Build-Protokolle",
    loadingBuildStatus: "Build-Status wird geladen...",
    buildQueued: "Build ist in der Warteschlange...",
    buildInProgress: "Build läuft...",
    buildCompletedReady: "Build abgeschlossen. Das Projekt ist bereit zum Starten.",
    currentStatus: "Aktueller Status",
    liveStream: "Live-Stream",
    buildFailedReview: "Build fehlgeschlagen. Prüfe die Protokolle und aktualisiere deinen Upload.",
    backToUpload: "Zurück zum Upload",
    buildCompletedSuccess: "Build erfolgreich abgeschlossen.",
    openProject: "Projekt öffnen",
    noLogsYet: "Noch keine Protokolle vorhanden...",
    noDeployLogsYet: "Noch keine Deploy-Protokolle vorhanden...",
    couldNotFetchBuildStatus: "Build-Status konnte nicht geladen werden. Bitte erneut versuchen.",
    opsMonitor: "Ops Monitor",
    appliedSciences: "Applied Sciences",
    useAdminToken: "Verwende ein Admin-Token, um Live-Quotenmetriken zu laden.",
    pasteAdminJwt: "Admin-JWT-Token einfügen",
    loading: "Wird geladen...",
    loadMonitor: "Monitor laden",
    trackedUsers: "Erfasste Nutzer",
    queuedBuilding: "Wartend / Im Build",
    runningProjects: "Laufende Projekte",
    courseQuotaHealth: "Kurs-Quota-Status (ACS / ADS)",
    runningSuffix: "laufend",
    userQuotaRiskTable: "Nutzer-Quota-Risikotabelle",
    user: "Nutzer",
    uploads24h: "Uploads 24h",
    queueLoad: "Queue-Last",
    risk: "Risiko",
    enterAdminToken: "Bitte Admin-JWT-Token eingeben.",
    failedMonitoringData: "Monitoring-Daten konnten nicht geladen werden.",
    ssoPlaceholder: "SSO wird angebunden, sobald die Zugangsdaten bereitstehen.",
  },
};

export function getLanguage() {
  const saved = localStorage.getItem(LANGUAGE_KEY);
  return saved === "en" ? "en" : "de";
}

export function setLanguage(language) {
  const next = language === "en" ? "en" : "de";
  localStorage.setItem(LANGUAGE_KEY, next);
  window.dispatchEvent(new CustomEvent("hof-language-change", { detail: next }));
}

export function onLanguageChange(listener) {
  const handler = (event) => listener(event.detail || getLanguage());
  window.addEventListener("hof-language-change", handler);
  return () => window.removeEventListener("hof-language-change", handler);
}

export function t(language, key) {
  return TEXT[language]?.[key] || TEXT.de[key] || key;
}

export function translateRole(role, language) {
  const normalized = String(role || "viewer").toLowerCase();
  return t(language, normalized);
}
